version: '3.7'
networks:
  app-network:
    driver: bridge
services:
    webservices:
        image: 'nginx:latest'
        container_name: webservices
        tty: true
        working_dir: /var/www/sandbox
        volumes:
          - './project:/var/www/sandbox'
          - './docker/nginx/hosts.conf:/etc/nginx/conf.d/hosts.conf'

        ports:
          - '8000:8000'
        depends_on:
          - sandbox
          - mysql
        networks:
          - app-network
    sandbox:
        container_name: sandbox
        build:
            context: ./docker/php_8.0
            dockerfile: Dockerfile                    
        working_dir: /var/www/sandbox
        volumes:
            - './project:/var/www/sandbox'
            - './docker/php_8.0/local.ini:/usr/local/etc/php/conf.d/local.ini'
        depends_on:
            - mysql      
        networks: 
            - app-network
        ports:
          - '6001:6001'
        expose:
         - "6001"          
    mysql:
        image: mysql:5.7.34
        container_name: mysql
        tty: true
        ports:
          - '3306:3306'
        volumes:
            - './docker/database:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secretuser
        networks: 
            - app-network
volumes:
  database: null
  

            
        